"""empty message

Revision ID: 967742596130
Revises: 77855ab100bd
Create Date: 2020-06-27 19:59:24.351933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967742596130'
down_revision = '77855ab100bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_subject_teacher_unit', 'classes', ['subject_id', 'teacher_id', 'unit_id'])
    op.create_unique_constraint('unique_exam_date_class', 'exams', ['exam_date', 'class_id'])
    op.create_unique_constraint('unique_exam_student', 'grades', ['exam_id', 'student_id'])
    op.create_unique_constraint('unique_name_guardian', 'students', ['name', 'guardian_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_name_guardian', 'students', type_='unique')
    op.drop_constraint('unique_exam_student', 'grades', type_='unique')
    op.drop_constraint('unique_exam_date_class', 'exams', type_='unique')
    op.drop_constraint('unique_subject_teacher_unit', 'classes', type_='unique')
    # ### end Alembic commands ###
