"""empty message

Revision ID: 97c6313163f8
Revises: b6522bf0ed65
Create Date: 2020-06-20 22:23:03.358666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c6313163f8'
down_revision = 'b6522bf0ed65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'enabled')
    # ### end Alembic commands ###
