"""empty message

Revision ID: bac65555d177
Revises: a6f398cb7d5b
Create Date: 2020-06-27 22:38:35.331145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac65555d177'
down_revision = 'a6f398cb7d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_class_student_date', 'presences', ['class_id', 'student_id', 'presence_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_class_student_date', 'presences', type_='unique')
    # ### end Alembic commands ###
