"""empty message

Revision ID: ceace16cc11d
Revises: 97c6313163f8
Create Date: 2020-06-20 22:28:33.516028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceace16cc11d'
down_revision = '97c6313163f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.alter_column('users', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('users', 'clearance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clearance', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.alter_column('users', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('user_types')
    # ### end Alembic commands ###
