"""empty message

Revision ID: f213a7f83294
Revises: ebc53b13f623
Create Date: 2020-07-04 20:53:11.715263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f213a7f83294'
down_revision = 'ebc53b13f623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pessoa', 'identificador_numero',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('pessoa', 'identificador_tipo',
               existing_type=postgresql.ENUM('CPF', 'RG', 'Certidão', name='tipo_identificador'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pessoa', 'identificador_tipo',
               existing_type=postgresql.ENUM('CPF', 'RG', 'Certidão', name='tipo_identificador'),
               nullable=False)
    op.alter_column('pessoa', 'identificador_numero',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
